services:
  - type: web
    name: library-management
    env: java
    buildCommand: mvn clean install
    startCommand: mvn spring-boot:run
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 17
    autoDeploy: true
    repo: https://github.com/pranshu-oz/Library-Management.git
    branch: main
    healthCheckPath: /
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: ${DATABASE_URL}
      - key: SPRING_DATASOURCE_USERNAME
        value: ${DATABASE_USERNAME}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${DATABASE_PASSWORD}

databases:
  - name: library-db
    plan: free
    type: MySql
